name: pull-request
  
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - 'dev'

env: 
  REPOSITORY_NAME: "pull-request-vote-pr-${{ github.event.pull_request.number }}"
  OVERLAY_PATH: "manifests/overlays/pr-${{ github.event.pull_request.number }}"
  WEBSITE_PORT: $(echo $((30000 + ${{ github.event.pull_request.number }})))

jobs:
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.KEY  }}
            HOSTNAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USERNAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            #Now we have got the access of EC2 and we will start the deploy .
           cd /home/ubuntu/test &&
           touch tttt4.txt
            '
  
